// <auto-generated />
using System;
using InvoiceTask.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InvoiceTask.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200622174301_seed data")]
    partial class seeddata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InvoiceTask.Models.Entities.Invoice", b =>
                {
                    b.Property<int>("InvoiceNO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Net")
                        .HasColumnType("money");

                    b.Property<int>("Storeid")
                        .HasColumnType("int");

                    b.Property<decimal>("Taxes")
                        .HasColumnType("money");

                    b.Property<decimal>("Total")
                        .HasColumnType("money");

                    b.HasKey("InvoiceNO")
                        .HasName("InvoiceNO");

                    b.HasIndex("Storeid");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            InvoiceNO = 1,
                            InvoiceDate = new DateTime(2020, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Net = 428m,
                            Storeid = 1,
                            Taxes = 7m,
                            Total = 400m
                        },
                        new
                        {
                            InvoiceNO = 2,
                            InvoiceDate = new DateTime(2020, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Net = 642m,
                            Storeid = 2,
                            Taxes = 7m,
                            Total = 600m
                        },
                        new
                        {
                            InvoiceNO = 3,
                            InvoiceDate = new DateTime(2020, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Net = 1070m,
                            Storeid = 3,
                            Taxes = 7m,
                            Total = 1000m
                        });
                });

            modelBuilder.Entity("InvoiceTask.Models.Entities.InvoiceItems", b =>
                {
                    b.Property<int>("invoiceItemsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Discount")
                        .HasColumnType("money");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Net")
                        .HasColumnType("money");

                    b.Property<decimal>("Total")
                        .HasColumnType("money");

                    b.Property<int>("invoiceId")
                        .HasColumnType("int");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<int>("unit")
                        .HasColumnType("int");

                    b.HasKey("invoiceItemsId")
                        .HasName("invoiceItemsId");

                    b.HasIndex("ItemId");

                    b.HasIndex("invoiceId");

                    b.ToTable("InvoiceItems");

                    b.HasData(
                        new
                        {
                            invoiceItemsId = 1,
                            Discount = 0m,
                            ItemId = 1,
                            Net = 200m,
                            Total = 200m,
                            invoiceId = 1,
                            price = 10,
                            quantity = 20,
                            unit = 0
                        },
                        new
                        {
                            invoiceItemsId = 2,
                            Discount = 0m,
                            ItemId = 2,
                            Net = 200m,
                            Total = 200m,
                            invoiceId = 1,
                            price = 10,
                            quantity = 20,
                            unit = 0
                        },
                        new
                        {
                            invoiceItemsId = 3,
                            Discount = 0m,
                            ItemId = 4,
                            Net = 200m,
                            Total = 200m,
                            invoiceId = 2,
                            price = 10,
                            quantity = 20,
                            unit = 0
                        },
                        new
                        {
                            invoiceItemsId = 4,
                            Discount = 0m,
                            ItemId = 5,
                            Net = 200m,
                            Total = 200m,
                            invoiceId = 2,
                            price = 10,
                            quantity = 20,
                            unit = 0
                        },
                        new
                        {
                            invoiceItemsId = 5,
                            Discount = 0m,
                            ItemId = 6,
                            Net = 200m,
                            Total = 200m,
                            invoiceId = 2,
                            price = 10,
                            quantity = 20,
                            unit = 0
                        },
                        new
                        {
                            invoiceItemsId = 6,
                            Discount = 0m,
                            ItemId = 7,
                            Net = 200m,
                            Total = 200m,
                            invoiceId = 3,
                            price = 10,
                            quantity = 20,
                            unit = 0
                        },
                        new
                        {
                            invoiceItemsId = 7,
                            Discount = 0m,
                            ItemId = 8,
                            Net = 200m,
                            Total = 200m,
                            invoiceId = 3,
                            price = 10,
                            quantity = 20,
                            unit = 0
                        },
                        new
                        {
                            invoiceItemsId = 8,
                            Discount = 0m,
                            ItemId = 9,
                            Net = 200m,
                            Total = 200m,
                            invoiceId = 3,
                            price = 10,
                            quantity = 20,
                            unit = 0
                        },
                        new
                        {
                            invoiceItemsId = 9,
                            Discount = 0m,
                            ItemId = 10,
                            Net = 200m,
                            Total = 200m,
                            invoiceId = 3,
                            price = 10,
                            quantity = 20,
                            unit = 0
                        },
                        new
                        {
                            invoiceItemsId = 10,
                            Discount = 0m,
                            ItemId = 11,
                            Net = 200m,
                            Total = 200m,
                            invoiceId = 3,
                            price = 10,
                            quantity = 20,
                            unit = 0
                        });
                });

            modelBuilder.Entity("InvoiceTask.Models.Entities.Item", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<decimal>("price")
                        .HasColumnType("money");

                    b.Property<int>("storeId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("storeId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "item_1",
                            price = 10m,
                            storeId = 1
                        },
                        new
                        {
                            id = 2,
                            name = "item_2",
                            price = 10m,
                            storeId = 1
                        },
                        new
                        {
                            id = 3,
                            name = "item_3",
                            price = 10m,
                            storeId = 1
                        },
                        new
                        {
                            id = 4,
                            name = "item_4",
                            price = 10m,
                            storeId = 2
                        },
                        new
                        {
                            id = 5,
                            name = "item_5",
                            price = 10m,
                            storeId = 2
                        },
                        new
                        {
                            id = 6,
                            name = "item_6",
                            price = 10m,
                            storeId = 2
                        },
                        new
                        {
                            id = 7,
                            name = "item_7",
                            price = 10m,
                            storeId = 3
                        },
                        new
                        {
                            id = 8,
                            name = "item_8",
                            price = 10m,
                            storeId = 3
                        },
                        new
                        {
                            id = 9,
                            name = "item_9",
                            price = 10m,
                            storeId = 3
                        },
                        new
                        {
                            id = 10,
                            name = "item_10",
                            price = 10m,
                            storeId = 3
                        },
                        new
                        {
                            id = 11,
                            name = "item_11",
                            price = 10m,
                            storeId = 3
                        });
                });

            modelBuilder.Entity("InvoiceTask.Models.Entities.Store", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "Store_1"
                        },
                        new
                        {
                            id = 2,
                            name = "Store_2"
                        },
                        new
                        {
                            id = 3,
                            name = "Store_3"
                        });
                });

            modelBuilder.Entity("InvoiceTask.Models.Entities.Invoice", b =>
                {
                    b.HasOne("InvoiceTask.Models.Entities.Store", "Store")
                        .WithMany()
                        .HasForeignKey("Storeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InvoiceTask.Models.Entities.InvoiceItems", b =>
                {
                    b.HasOne("InvoiceTask.Models.Entities.Item", "Items")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvoiceTask.Models.Entities.Invoice", "Invoice")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("invoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InvoiceTask.Models.Entities.Item", b =>
                {
                    b.HasOne("InvoiceTask.Models.Entities.Store", "Store")
                        .WithMany()
                        .HasForeignKey("storeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
